Add topic for CSS Modules
github/explore pull request #1882
Opened 2020-10-23 19:45 UTC by david-fong

### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Modularity in programming languages can be used to improve the robustness of a system, and to prevent conflicts between dependencies. I believe that many developers would find CSS Modules useful- if only they knew that such a thing existed. I hope that creating this topic will help developers discover it.

2020-10-28 20:02 UTC, iancanderson requested changes
The logo looks a bit grainy. Could you find or generate a sharper looking image? Thanks!

2020-10-29 07:43 UTC, david-fong commented on topics/css-modules/index.md
> +# released: May 25, 2015
done!

2020-10-29 13:04 UTC, iancanderson commented on topics/css-modules/index.md
> +# released: May 25, 2015
```suggestion
```

2020-10-30 18:47 UTC, iancanderson approved these changes
Thanks!

2020-10-30 18:48 UTC, merged