Add Minetest topic
github/explore pull request #2185
Opened 2021-03-09 01:18 UTC by Panquesito7

### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------
### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> I think this topic should be added because it has over 500+ repositories with this topic, lots of mods, libraries, and tools for the engine. It's a nice project and game engine. I like it and use it. Many people use it and like it.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

2021-03-09 20:19 UTC, iancanderson approved these changes
Thanks!

2021-03-09 20:20 UTC, iancanderson requested changes
Ah, I didn't notice this at first, but CI is failing. Could you fix up the failures described here: https://github.com/github/explore/runs/2061940573

Thanks!

2021-03-10 01:40 UTC, Panquesito7 commented
> but CI is failing

Continuous integration issues, should be fixed now. Please review again. Thanks. 🙂

2021-03-10 15:04 UTC, iancanderson approved these changes

2021-03-10 15:05 UTC, merged