Add Nunjucks
github/explore pull request #2372
Opened 2021-06-05 00:17 UTC by Nixinova

### Requirements

- [x] I followed the [contributing guidelines](https://github.com/github/explore/blob/master/CONTRIBUTING.md)
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

------

### Change type

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub
- [x] My folder contains a `*.png` image and `index.md`
- [x] All required fields in my `index.md` conform to the [Style Guide and API docs](https://github.com/github/explore/tree/master/docs)

Nunjucks is a popular templating language bundled with the popular [Eleventy](https://GitHub.com/topics/Eleventy) build tool. There are [over 750](https://github.com/topics/nunjucks) repos tagged with Nunjucks

--------
Sidenote, I think using squash-&-merge would be a better option for this repo

2021-06-07 00:59 UTC, devkadirselcuk approved these changes

2021-06-07 00:59 UTC, devkadirselcuk approved these changes

2021-06-07 15:33 UTC, smashwilson requested changes
👋🏻 It looks like there are a few CI failures here:

```
  1) Failure:
topics::nunjucks topic#test_0019_has at most one image with the right name, type, and dimensions [/home/runner/work/explore/explore/test/topics_test.rb:229]:
topic images should be 288px wide.
Expected: 288
  Actual: 900

  2) Failure:
topics::nunjucks topic#test_0017_has matching logo, when logo key exists [/home/runner/work/explore/explore/test/topics_test.rb:198]:
should not specify logo nunjucks.png when file does not exist

  3) Failure:
topics::nunjucks topic#test_0018_has a matching logo key, when logo exists [/home/runner/work/explore/explore/test/topics_test.rb:212]:
logo key should be nunjucks.jpg, but was nunjucks.png
```

Resizing the logo file to 288px on a side and changing the `logo:` key to match should get things fixed up 🔧

2021-06-07 15:33 UTC, smashwilson commented on topics/nunjucks/index.md
> +logo: nunjucks.png
The logo file extension is mismatched here:

```suggestion
logo: nunjucks.jpg
```

2021-06-08 18:52 UTC, devkadirselcuk approved these changes

2021-06-09 13:21 UTC, smashwilson approved these changes

2021-06-09 13:21 UTC, smashwilson commented
Thanks!

2021-06-09 13:22 UTC, merged