Create PHP frameworks
github/explore pull request #2474
Opened 2021-07-31 21:36 UTC by Ahmed-Ibrahimm

### Thank you for contributing! Please confirm this pull request meets the following requirements:

- [x]  I followed the contributing guidelines: https://github.com/github/explore/blob/master/CONTRIBUTING.md

- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---------------------------------------------------------------------

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288)
- [x] Content (and my changes are in `index.md`)

> This is a new category that refers to PHP frameworks and it is very important as developer references

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> This is a new category that refers to PHP frameworks and it is very important as developer references .

### Something that does not neatly fit into the binary options above

- [x] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [x] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of your proposed changes.

---------------------------------------------------------------------

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

2021-07-31 23:09 UTC, MobarakeGH approved these changes

2021-08-01 00:01 UTC, Ahmed-Ibrahimm commented
I hope you merge this pull request in your repo, thanks

2021-08-02 08:49 UTC, kenyonj requested changes
I'm thinking that we should change the collection name to be pluralised. What do you think?

`PHP Framework` -> `PHP Frameworks`

this will require a directory name change as well as editing the `display_name`

2021-08-02 11:55 UTC, Ahmed-Ibrahimm commented
> I'm thinking that we should change the collection name to be pluralised. What do you think?
> 
> `PHP Framework` -> `PHP Frameworks`
> 
> this will require a directory name change as well as editing the `display_name`

Done

2021-08-02 16:20 UTC, kenyonj approved these changes

2021-08-02 16:27 UTC, merged