Add new topic: scapy
github/explore pull request #2652
Opened 2021-10-02 16:38 UTC by Joe-Sin7h

### Please confirm this pull request meets the following requirements:

- [X] I followed the contributing guidelines: <https://github.com/github/explore/blob/master/CONTRIBUTING.md>.
- [X] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [X] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [X] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/scapy` or `https://github.com/collections/scapy`)
- [X] My folder contains a `*.png` image (if applicable) and `index.md`
- [X] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/master/docs>

> Scapy has become very popular and it's a powerful interactive packet manipulation program, that's why I think this topic should be curated.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/master/docs

> Please replace this line with an explanation of your proposed changes.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

2021-10-02 17:58 UTC, guedou commented
Some information provided in this PR are incorrect. I will try to provide feedback ASAP.

2021-10-02 18:02 UTC, Joe-Sin7h commented
> Some information provided in this PR are incorrect. I will try to provide feedback ASAP.

sure, let me know so I can fix them.

2021-10-03 08:24 UTC, guedou reviewed
Could you apply these changes?

2021-10-03 08:24 UTC, guedou commented on topics/scapy/index.md
> +display_name: scapy
The official writing is `Scapy`

2021-10-03 08:24 UTC, guedou commented on topics/scapy/index.md
> +released: April 19, 2021
It was released on March 26, 2003.

2021-10-03 08:24 UTC, guedou commented on topics/scapy/index.md
> +short_description: Scapy is a powerful interactive packet manipulation program.
Could you use:
`Scapy is a Python-based interactive packet manipulation program & library. It upports Python 2 & Python 3.`

2021-10-03 08:24 UTC, guedou commented on topics/scapy/index.md
> +related: scapy, python
Is `scapy` useful in this context?

2021-10-03 08:56 UTC, Joe-Sin7h commented
> Could you apply these changes?

Thanks for reviewing them, I have now made the required changes.

2021-10-03 12:27 UTC, guedou reviewed
It looks OK. Thanks!

2021-10-04 07:50 UTC, kenyonj approved these changes
💯 🍨 Thank you for your contribution! I'll merge this in as soon as CI is 🍏

(I'll make the suggested change)

2021-10-04 07:50 UTC, kenyonj commented on topics/scapy/index.md
> +aliases: scapy
Since `scapy` is the topic name, it can't be listed as an alias as well.
```suggestion
```

2021-10-04 08:02 UTC, kenyonj requested changes
Looks like there are still CI issues. Specifically:

```
topics::scapy topic#test_0019_has at most one image with the right name, type, and dimensions [/home/runner/work/explore/explore/test/topics_test.rb:229]:
topic images should be 288px wide.
Expected: 288
  Actual: 595
```

2021-10-04 09:26 UTC, Joe-Sin7h commented
@kenyonj Thanks, I'll add a different image now.

2021-10-04 09:41 UTC, kenyonj approved these changes

2021-10-04 09:56 UTC, Joe-Sin7h commented
@kenyonj can you merge it now :)
Thank you for reviewing.

2021-10-04 10:00 UTC, merged