Add framer-motion topic
github/explore pull request #2729
Opened 2021-11-27 14:49 UTC by rbourdon

### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/master/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/master/docs>

> Framer motion is a popular animation library for react with almost 100k dependents and 1k public repositories using the topic.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

2021-11-30 03:48 UTC, 07823226672 reviewed
ᎪHMᎬD ᎪᏞHᎪRES

2021-12-01 17:18 UTC, MikeMcQuaid approved these changes

2021-12-02 09:51 UTC, MikeMcQuaid requested changes
Thanks for the PR!

Also need to update the image: https://github.com/github/explore/runs/4392946945?check_suite_focus=true#step:7:418

2021-12-02 09:51 UTC, MikeMcQuaid commented on topics/framer-motion/index.md
> +aliases: motion, framer-motion
```suggestion
aliases: motion
```

2021-12-03 15:43 UTC, MikeMcQuaid approved these changes

2021-12-03 15:44 UTC, merged

2021-12-03 15:44 UTC, MikeMcQuaid commented
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @rbourdon!