Add react-router topic
github/explore pull request #2877
Opened 2022-01-23 10:57 UTC by sidx8

### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/master/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?
  - [x] Curating a new topic or collection
---

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/master/docs>

> Please replace this line with an explanation of why you think this topic or collection should be curated.

2022-01-23 13:52 UTC, Luois45 commented
@sidx8 The logo should have the dimensions of 288x288 pixels.

2022-01-24 11:29 UTC, sidx8 commented
@Luois45 I have updated the image can you review this

2022-01-24 11:33 UTC, Luois45 commented
@sidx8 I can't review it because I'm not the code owner but it does look fine now. 👍

2022-01-24 17:18 UTC, sidx8 reviewed
created the react-router topic and added a logo

2022-01-25 10:46 UTC, kenyonj requested changes
Some small changes and then we can get this merged!

2022-01-25 10:46 UTC, kenyonj commented on topics/react-router/index.md
> +aliases: react-router, react router
This list cannot include the topic name or phrases
```suggestion
```

2022-01-25 10:46 UTC, kenyonj commented on topics/react-router/index.md
> +display_name: react-router
The display name is usually the way the name looks in contexts where it's being written about as a proper noun.
```suggestion
display_name: React Router
```

2022-01-27 10:47 UTC, kenyonj approved these changes
💯 🍨 Thank you for your contribution! I'll merge this in as soon as CI is 🍏

2022-01-27 11:01 UTC, merged