add iot topic
github/explore pull request #2945
Opened 2022-02-15 13:11 UTC by StokicDusan

### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/master/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/master/docs>

> It's on the `topics-todo.md` list

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

2022-02-18 11:07 UTC, kenyonj submitted a review, later dismissed
Just a couple comments and then we can run CI

2022-02-18 11:07 UTC, kenyonj commented on topics/iot/index.md
> +aliases: IoT, Internet-of-things
These are case insensitive so we don’t want a duplicate of the topic name here. 
```suggestion
aliases: Internet-of-things
```

2022-02-18 11:07 UTC, kenyonj commented on topics/iot/index.md
> +short_description: The iot is a network of devices which exchanging data with other devices and systems over the internet.
```suggestion
short_description: The iot is a network of devices that exchange data with other devices and systems over the internet.
```

2022-02-19 15:48 UTC, StokicDusan commented
Committed changes suggested by @kenyonj

2022-02-24 03:20 UTC, octokatherine requested changes
👋  @StokicDusan, there is a syntax error causing CI failures, I left a suggested change!

2022-02-24 03:20 UTC, octokatherine commented on topics/iot/index.md
> +--
```suggestion
---
```

2022-02-25 00:55 UTC, hodies528 reviewed
完美的诠释

2022-03-03 09:12 UTC, MikeMcQuaid approved these changes
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @StokicDusan!

2022-03-03 09:12 UTC, merged