Create topics/data/index.md
github/explore pull request #3154
Opened 2022-06-30 11:37 UTC by e1e0

### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Curating a new topic or collection

---

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

**11,195 public repositories, no description, a popular topic.**

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

2022-06-30 22:12 UTC, smashwilson requested changes

2022-06-30 22:12 UTC, smashwilson commented on topics/data/index.md
> +short_description: Facts and statistics (numerical data), these may be analysed.
I think this reads better without the comma:

```suggestion
short_description: Facts and statistics (numerical data) that may be analysed.
```

2022-07-03 01:05 UTC, e1e0 commented
Need some help...
```
  1) Failure:
collections::made-in-italy collection#test_0013_fails if a user, organization, or repository has been renamed or removed [/home/runner/work/explore/explore/test/collections_test.rb:197]:
Expected ["made-in-italy: federico-terzi/espanso has been renamed to espanso/espanso"] to be empty.
1050 runs, 2608 assertions, 1 failures, 0 errors, 0 skips
Error: made-in-italy: federico-terzi/espanso has been renamed to espanso/espanso
```

2022-07-03 11:51 UTC, smashwilson approved these changes

2022-07-03 11:52 UTC, smashwilson commented
Thanks!

2022-07-03 11:52 UTC, merged