Create index.md
github/explore pull request #3264
Opened 2022-09-06 06:32 UTC by msupernaut

### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [x] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

Testing is an important discipline in DevSecOps. I've curated a collection of open source tools and frameworks that helps testing teams to ship code faster. These are frameworks like Selenium, Appium , Playwright, Cypress etc that are widely used by OSS teams and enterprises alike - as well as tools that help create/write test cases. 

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [x] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/main/docs

> Please replace this line with an explanation of your proposed changes.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

2022-09-06 15:20 UTC, kenyonj requested changes
Thanks for the PR. Couple of comments. Unfortunately our current implementation is case sensitive so we'll need to update a couple of the repo references.

2022-09-06 15:20 UTC, kenyonj commented on collections/OpenSource-Testing/index.md
> + - eWert-Online/osnap
```suggestion
 - eWert-Online/OSnap
```

2022-09-06 15:20 UTC, kenyonj commented on collections/OpenSource-Testing/index.md
> + - newsuk/ayespy
```suggestion
 - newsuk/AyeSpy
```

2022-09-06 15:20 UTC, kenyonj commented on collections/OpenSource-Testing/index.md
> +Open source projects to help testers/QA teams with testing tools and frameworks to automate software delivery with high quality
This looks like an incomplete sentence. What do you think about this?
```suggestion
Open source testing tools and frameworks to help testers/QA teams with automating and delivering high quality software.
```

2022-09-06 16:04 UTC, msupernaut commented
Thank you ! Made the updates !

2022-09-07 02:03 UTC, kenyonj approved these changes
Looks great. Thanks for your contribution!

2022-09-07 02:04 UTC, merged