Add anime topic
github/explore pull request #3320
Opened 2022-10-02 08:03 UTC by Nekidev

### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

> Anime has become really popular over the years. There are many projects with this topic, so some information should be added.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [x] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/main/docs

> Added the `anime` topic. This topic's description was taken from [Wikipedia](https://en.wikipedia.org/wiki/Anime).

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

2022-10-02 08:42 UTC, SatoshiNakamoto-MAM commented
Sorry im the creater of blockchain and bitcoin i am satoshi nakamoto

On Sun, Oct 2, 2022, 1:03 AM Neki ***@***.***> wrote:

> Please confirm this pull request meets the following requirements:
>
>    - I followed the contributing guidelines:
>    https://github.com/github/explore/blob/main/CONTRIBUTING.md.
>    - I have no affiliation with the project I am suggesting (as a
>    maintainer, creator, contractor, or employee).
>
> Which change are you proposing?
>
>    - Suggesting edits to an existing topic or collection
>    - Curating a new topic or collection
>    - Something that does not neatly fit into the binary options above
>
> ------------------------------
> Editing an existing topic or collection
>
> I'm suggesting these edits to an existing topic or collection:
>
>    - Image (and my file is *.png, square, dimensions 288x288, size <= 75
>    kB)
>    - Content (and my changes are in index.md)
>
> Please replace this line with an explanation of why you think these
> changes should be made.
>
> Curating a new topic or collection
>
>    - I've formatted my changes as a new folder directory, named for the
>    topic or collection as it appears in the URL on GitHub (e.g.
>    https://github.com/topics/[NAME] or
>    https://github.com/collections/[NAME])
>    - My folder contains a *.png image (if applicable) and index.md
>    - All required fields in my index.md conform to the Style Guide and
>    API docs: https://github.com/github/explore/tree/main/docs
>
> Anime has become really popular over the years. There are many projects
> with this topic, so some information should be added.
>
> Something that does not neatly fit into the binary options above
>
>    - My suggested edits are not about an existing topic or collection, or
>    at least not a single one
>    - My suggested edits are not about curating a new topic or collection,
>    or at least not a single one
>    - My suggested edits conform to the Style Guide and API docs:
>    https://github.com/github/explore/tree/main/docs
>
> Added the anime topic. This topic's description was taken from Wikipedia
> <https://en.wikipedia.org/wiki/Anime>.
>
> ------------------------------
>
> *Please note: we will close your PR without comment if you do not check
> the boxes above and provide ALL requested information.*
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/github/explore/pull/3320
> Commit Summary
>
>    - eba1ee2
>    <https://github.com/github/explore/pull/3320/commits/eba1ee2efef58eb41149dd743df4dfca427054c6>
>    Create index.md
>    - e7de91e
>    <https://github.com/github/explore/pull/3320/commits/e7de91e7f67e595c8f77b2046991bdd7d9e3c0bd>
>    Added image
>    - 6285246
>    <https://github.com/github/explore/pull/3320/commits/62852468c7a2f9073cdf2903185620b1907664b0>
>    Renamed image
>    - e2c65a2
>    <https://github.com/github/explore/pull/3320/commits/e2c65a20048897b5dce26a342170076c0c81c330>
>    Changed image format
>
> File Changes
>
> (2 files <https://github.com/github/explore/pull/3320/files>)
>
>    - *A* topics/anime/anime.png
>    <https://github.com/github/explore/pull/3320/files#diff-24a9335f4ba0c13ece51c82cc37165e36757c6565cf6736a2483e08d736c348c>
>    (0)
>    - *A* topics/anime/index.md
>    <https://github.com/github/explore/pull/3320/files#diff-7de2888a56902f332b887ca32082881afccd5d12487285ec81417084b734ee63>
>    (8)
>
> Patch Links:
>
>    - https://github.com/github/explore/pull/3320.patch
>    - https://github.com/github/explore/pull/3320.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/github/explore/pull/3320>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2JHXLGIZT3MESYSTTX3RWLWBE6W7ANCNFSM6AAAAAAQ2ZOKCM>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-10-06 14:56 UTC, kenyonj requested changes
Please address the CI failures and we can review. Thanks!

2022-10-09 18:23 UTC, Kristories reviewed
Images should not exceed 75,000 bytes, got 150,897 bytes

2022-10-09 18:23 UTC, Kristories commented on topics/anime/index.md
> +---
Logo key should be `anime.png`, but was missing

2022-10-13 12:49 UTC, ChristopherLeeFalck commented
> <!-- Thank you for contributing! -->
> 
> ### Please confirm this pull request meets the following requirements:
> 
> 
> 
> - [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
> 
> - [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).
> 
> 
> 
> ### Which change are you proposing?
> 
> 
> 
>   - [ ] Suggesting edits to an existing topic or collection
> 
>   - [x] Curating a new topic or collection
> 
>   - [ ] Something that does not neatly fit into the binary options above
> 
> 
> 
> ---
> 
> 
> 
> <!-- ⚠️ Please select either this section... ⚠️ -->
> 
> ### Editing an existing topic or collection
> 
> 
> 
> I'm suggesting these edits to an existing topic or collection:
> 
> - [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
> 
> - [ ] Content (and my changes are in `index.md`)
> 
> 
> 
> > Please replace this line with an explanation of why you think these changes should be made.
> 
> 
> 
> <!-- ⚠️ ... or this section ⚠️ -->
> 
> ### Curating a new topic or collection
> 
> 
> 
> - [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
> 
> - [x] My folder contains a `*.png` image (if applicable) and `index.md`
> 
> - [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>
> 
> 
> 
> > Anime has become really popular over the years. There are many projects with this topic, so some information should be added.
> 
> 
> 
> <!-- ⚠️ ... or this section ⚠️ -->
> 
> ### Something that does not neatly fit into the binary options above
> 
> 
> 
> - [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
> 
> - [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
> 
> - [x] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/main/docs
> 
> 
> 
> > Added the `anime` topic. This topic's description was taken from [Wikipedia](https://en.wikipedia.org/wiki/Anime).
> 
> 
> 
> ---
> 
> 
> 
> **Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**
> 
>

2022-10-21 02:27 UTC, IcebergVerse commented
bundle install
bundle exec rubocop

2022-10-24 21:57 UTC, closed without merging