add related to minecraft and minecraft-bedrock-edition topics
github/explore pull request #3411
Opened 2022-11-29 19:56 UTC by AdamRaichu

### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [x] Content (and my changes are in `index.md`)

This PR adds related field to topics `minecraft` and `minecraft-bedrock-edition`.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

2022-11-29 20:04 UTC, AdamRaichu commented
I see that a check failed because there are the same topics in both related and aliases. I feel that they make sense in both[*]. However, should I close?

2022-11-30 16:32 UTC, kenyonj commented
> I see that a check failed because there are the same topics in both related and aliases. I feel that they make sense in both. However, should I close?

I believe the failure is saying that in each topic the related and alias lists can't have any overlap. So you'll just need to make sure that each list has unique items.

2022-11-30 17:02 UTC, kenyonj requested changes

2022-12-01 21:27 UTC, kenyonj reviewed
💯 🍨 Thank you for your contribution!

2022-12-01 21:27 UTC, kenyonj approved these changes

2022-12-01 21:28 UTC, merged