Added azure-devops topic
github/explore pull request #3462
Opened 2022-12-29 13:27 UTC by brunobritorj

### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

> The azure-devops topic has more than 1.3k repositories linked but so far it wasn't a curated topic.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/main/docs

> Please replace this line with an explanation of your proposed changes.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

2022-12-29 20:34 UTC, kenyonj approved these changes
💯 🍨 Thank you for your contribution! I'll merge this in as soon as CI is 🍏

2022-12-29 20:37 UTC, kenyonj requested changes
Looks like there are several failures that need to be addressed. Please take a look at the CI results for more information.

2022-12-29 20:37 UTC, kenyonj commented on topics/azure-devops/index.md
> +released: 2005, formerly Team Foundation Server (TFS) and Azure DevOps Server
```suggestion
released: 2005
```

2022-12-29 20:37 UTC, kenyonj commented on topics/azure-devops/index.md
> +short_description: Azure DevOps is a Microsoft product that provides version control, reporting, requirements/project management, and automated builds/tests/release capabilities.
This needs to be shortened a bit

2022-12-30 17:34 UTC, brunobritorj commented on topics/azure-devops/index.md
> +short_description: Azure DevOps is a Microsoft product that provides version control, reporting, requirements/project management, and automated builds/tests/release capabilities.
Done

2022-12-30 17:35 UTC, brunobritorj commented
Hi Justin,
Sure, I fixed them.
Thanks!

2022-12-30 22:49 UTC, kenyonj approved these changes

2022-12-30 22:50 UTC, kenyonj requested changes
Still a failure around the image dimensions.

2022-12-31 10:38 UTC, brunobritorj commented
> Still a failure around the image dimensions.

Fixed. 288x288px with transparent background.

2022-12-31 14:35 UTC, kenyonj approved these changes

2023-01-02 13:15 UTC, MikeMcQuaid requested changes
@brunobritorj Please rebase this on top of `master` or merge in `master`, this has merge conflicts that need resolved. Thanks!

2023-01-02 14:20 UTC, merged

2023-01-02 16:23 UTC, brunobritorj commented
Thanks @MikeMcQuaid !

2023-01-02 16:32 UTC, MikeMcQuaid commented
Thanks @brunobritorj!