add topic "motorola-68000"
github/explore pull request #3475
Opened 2023-01-04 14:07 UTC by Wladefant

### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [x] Content (and my changes are in `index.md`)

> Motorola 68000 is a microprocessor that has multiple assemblers, compilers, and operating systems. It is used in many personal computers, workstations, and game consoles, including the Apple Macintosh, Atari ST, Commodore Amiga, and the Nintendo Entertainment System.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

> This topic is not curated right now and has no explanations

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/main/docs

> see index.md

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

2023-01-04 14:27 UTC, Wladefant reviewed
deleted specification of logo.
deleted alias that is the same as topic name.

2023-01-04 21:08 UTC, kenyonj requested changes
Thanks for your contribution! There are some changes that need to be made for CI.

2023-01-04 21:08 UTC, kenyonj commented on topics/motorola-68000/index.md
> +related: assembly, cpu, microprocessor, processor, 68k-assembly, cpm-68000, assembly-68000, cpm-68k, motorola-6809, motorola-68020, motorola-68030, motorola-68040, motorola-68060, m68k-atari-mint, 68
duplicated
```suggestion
related: assembly, cpu, microprocessor, processor, 68k-assembly, cpm-68000, assembly-68000, cpm-68k, motorola-6809, motorola-68020, motorola-68030, motorola-68040, motorola-68060, m68k-atari-mint, 6800, m68k-disassembler, m68k-assembly, m68k-elf-gcc, assembly-m68k, m68k-emulation, motorola-6805
```

2023-01-04 21:08 UTC, kenyonj commented on topics/motorola-68000/index.md
> +
no need for this blank line
```suggestion
```

2023-01-04 21:18 UTC, kenyonj commented
Looks like the related list has to be trimmed down now:

```
should have no more than 10 related topics
```

2023-01-04 21:23 UTC, kenyonj requested changes

2023-01-04 21:23 UTC, kenyonj commented on topics/motorola-68000/index.md
> +
`m68k-assembly` is still duplicated and there is still a blank line, removing both here:
```suggestion
related: 68k-assembly, assembly-68000, m68k-atari-mint, m68k-assembly, m68k-disassembler, m68k-elf-gcc, assembly-m68k, m68k-emulation, motorola-6805
```

2023-01-05 09:23 UTC, Wladefant commented
Ready?

2023-01-05 14:50 UTC, kenyonj approved these changes
Looks great. Thanks for your contribution!

2023-01-05 14:50 UTC, merged