Add relevant info in WordPress topic
github/explore pull request #3650
Opened 2023-03-26 16:19 UTC by alelazcano

### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [x] Content (and my changes are in `index.md`)

> Changes: Add relevant info WordPress:
> - add relevant aliases
> - fix and add info in short description
> - add context and relevant info in large description

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.** ✅

2023-03-27 21:03 UTC, kenyonj requested changes

2023-03-27 21:03 UTC, kenyonj commented on topics/wordpress/index.md
> +aliases: wordpress-development, wordpress-site, wordpress-theme, wordpress-plugin,automattic,woocommerce
these seem more "related" than aliases. What do you think about putting them in a related list?
```suggestion
aliases: wordpress-development, wordpress-site
related: wordpress-theme, wordpress-plugin, automattic, woocommerce
```

2023-03-27 21:03 UTC, kenyonj commented on topics/wordpress/index.md
> +Some reports say that WordPress represents around 35% of the sites on the public internet.
This doesn't feel right to have here, almost like marketing. Can we remove?
```suggestion
```

2023-04-21 02:57 UTC, chardso commented
https://github.com/github/explore/pull/3650#issue-1640976087
This seems to have taken long,get through it such that we update the info.

2023-06-02 21:52 UTC, ahpook approved these changes

2023-06-02 22:11 UTC, ahpook commented
@kenyonj i went ahead and committed the changes you suggested 👍

2023-06-05 23:41 UTC, merged