Add relevant new info to Symfony topic
github/explore pull request #3656
Opened 2023-03-26 22:03 UTC by alelazcano

### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [x] Content (and my changes are in `index.md`)

> Add relevant new info to Symfony topic, before 6y ago last commit.

2023-03-27 21:21 UTC, kenyonj requested changes

2023-04-25 06:04 UTC, Budgurl commented on topics/symfony/index.md
> +related: prestashop, laravel, cakephp, codeigniter, php, php-framework, php-component, php-library, php-package
There are some other ways

2023-05-09 22:53 UTC, shahin7071 commented
> `

2023-05-09 22:53 UTC, shahin7071 commented
12

2023-06-02 22:20 UTC, ahpook commented
Closing this one as being spammy - it plagiarizes the copy from the website and has too many unrelated topics.

2023-06-02 22:20 UTC, closed without merging