Add Anime topic
github/explore pull request #3666
Opened 2023-04-03 14:22 UTC by Copy05

### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---
### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains ~~a `*.png` image (if applicable) and~~ `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

There's so many anime projects on github but no explaination what anime is that's why i wanted to add the anime topic to `github/explore` so that people can be informed what anime is when they're looking at the topic site

---

2023-04-05 20:37 UTC, kenyonj requested changes

2023-04-05 20:37 UTC, kenyonj commented on topics/anime/index.md
> +Anime (Japanese: アニメ, IPA: [aɲime] (listen)) is hand-drawn and computer-generated animation originating from Japan. Outside of Japan and in English, anime refers specifically to animation produced in
>anime refers specifically to animation produced in Japan.

I'm not sure this is true. From the existing topic page alone, there are tools that help you produce anime, which can be made from anywhere. Thoughts on removing this line?
```suggestion
Anime (Japanese: アニメ, IPA: [aɲime] (listen)) is hand-drawn and computer-generated animation often originating from Japan.
```

2023-04-06 05:05 UTC, Copy05 commented
You're right there's some animations that people concider as a anime that isnt from japan i've removed the line, thanks

2023-04-06 20:21 UTC, kenyonj approved these changes
💯 🍨 Thank you for your contribution! I'll merge this in as soon as CI is 🍏

2023-04-06 20:22 UTC, merged