Add businesscentralsamples topic
github/explore pull request #3718
Opened 2023-05-12 11:56 UTC by freddydk

### Please confirm this pull request meets the following requirements:

- [X] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [X] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [X] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Curating a new topic or collection

- [X] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [X] My folder contains a `*.png` image (if applicable) and `index.md`
- [X] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

We are creating a number of Open Source Business Central Samples in the Microsoft organization and would like to have a topic, where we and our partners can create demos and samples, easily locatable by other partners.

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

2023-05-13 10:56 UTC, xoshimovshohrux commented
### ****

2023-05-15 18:57 UTC, freddydk commented
Anything more I need to do here?

2023-05-18 13:48 UTC, ipc103 commented
👋 ❤️ Hi, thanks for contributing! Seems to me that the `bcsamples` topic is duplicative. I'm going to go ahead and remove that directory in favor of the `msdyn365bc` one. Let me know if I'm missing something and we can adjust in a future PR!

2023-05-19 14:50 UTC, ipc103 requested changes

2023-05-20 14:09 UTC, freddydk commented on topics/bcsamples/index.md
msdyn365bc was intended for everything that is related to Microsoft Dynamics 365 Business Central (today people use msdyn365bc, businesscentral, business-central or al) - this topic would be an attempt to streamline it. This can be samples, devops solutions, coding patterns or open-source projects.

bcsamples was intended for ready-to-use open-source samples for the same product - a place for partners to go and find a sample to fork at use as starting point and/or contribute to.

So, all bcsamples repositories would also have msdyn365bc, but all msdyn365bc will definitely not have bcsamples.

bcsamples would be the most important one for me at this time.

2023-05-22 20:52 UTC, ipc103 commented on topics/bcsamples/index.md
@freddydk Thanks for clarifying. As it stands, the content is too similar between them to justify the existence of two topics. I'd suggest that you either find a way to differentiate them more or just move forward with the bcsamples topic.

2023-05-23 14:59 UTC, freddydk commented on topics/bcsamples/index.md
will do

2023-05-26 00:47 UTC, ahpook approved these changes
LGTM!

2023-05-26 00:51 UTC, merged