Adding new React UI item in collections
github/explore pull request #3767
Opened 2023-06-17 09:25 UTC by officialrajdeepsingh

### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I have no affiliation with the project I am suggesting (as a maintainer, creator, contractor, or employee).

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

Adding new React UI items in collections. It contains a list of Morden UI libraries based on React.

2023-07-08 20:12 UTC, ahpook requested changes
The collection looks good, but please fix the description. Thanks for the contribution!

2023-07-08 20:12 UTC, ahpook commented on collections/react-ui/index.md
> +A React UI library or React component library of a collection of components. You can use it, and ready for production.
This wording could be improved.

```suggestion
A React UI library or collection of React components. React is an open source JavaScript framework for designing user interfaces.
```

2023-07-09 16:48 UTC, officialrajdeepsingh commented on collections/react-ui/index.md
> +A React UI library or React component library of a collection of components. You can use it, and ready for production.
Yes, thanks for help

2023-07-14 18:22 UTC, ipc103 commented
@officialrajdeepsingh - one (hopefully) last request here - we require the image name to match the name of the collection. Mind renaming `react.png` to `react-ui.png` to get our CI passing?

2023-07-16 16:33 UTC, Briancarl07 reviewed
Nice

2023-07-17 14:07 UTC, ipc103 approved these changes
👍 ❤️ Thanks for contributing!

2023-07-17 17:09 UTC, ahpook approved these changes

2023-07-17 17:10 UTC, merged