Add Clipboard Managers collection
github/explore pull request #3790
Opened 2023-07-06 15:27 UTC by SpongeJohnSquareLennon

### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I am not the sole author or employee of a company who created the topic or collection I'm changing.

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

> Clipboard managers are a great way to remember more things and are especially useful to users here on GitHub.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/main/docs

> Please replace this line with an explanation of your proposed changes.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

2023-07-08 20:39 UTC, ahpook requested changes
LGTM, please add an image reference and I will merge.

2023-07-08 20:39 UTC, ahpook commented on collections/clipboard-managers/index.md
> +created_by: SpongeJohnSquareLennon
The yaml needs a reference to the image or it won't display:
```suggestion
created_by: SpongeJohnSquareLennon
image: clipboard-managers.png
```

2023-07-13 17:36 UTC, SpongeJohnSquareLennon commented
@aphook, just fixed it, thanks!

2023-07-13 20:31 UTC, ahpook approved these changes
LGTM, thanks!

2023-07-13 20:32 UTC, merged