Add related to topic "Documentation"
github/explore pull request #3980
Opened 2023-10-12 06:13 UTC by shaedrich

### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I am not the sole author or employee of a company who created the topic or collection I'm changing.

### Which change are you proposing?

  - [x] Suggesting edits to an existing topic or collection
  - [ ] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [x] Content (and my changes are in `index.md`)

Types of documentation

### Curating a new topic or collection

- [ ] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [ ] My folder contains a `*.png` image (if applicable) and `index.md`
- [ ] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

> Please replace this line with an explanation of why you think this topic or collection should be curated.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/main/docs

> Please replace this line with an explanation of your proposed changes.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

2023-10-13 23:29 UTC, ahpook requested changes
1 change, otherwise LGTM

2023-10-13 23:29 UTC, ahpook commented on topics/documentation/index.md
> +wikipedia_url: https://en.wikipedia.org/wiki/Software_documentation,
```suggestion
wikipedia_url: https://en.wikipedia.org/wiki/Software_documentation
```
You added an extra comma on this URL

2023-10-13 23:30 UTC, shaedrich commented on topics/documentation/index.md
> +wikipedia_url: https://en.wikipedia.org/wiki/Software_documentation,
Good catch!

2023-10-13 23:35 UTC, ahpook approved these changes
Nice!

2023-10-13 23:36 UTC, merged

2023-10-14 00:07 UTC, ahpook commented
@shaedrich i just rebuilt the site, so all the changes you've made recently are live. Thanks so much for these contributions!

<img width="929" alt="Screenshot 2023-10-13 at 5 05 17 PM" src="https://github.com/github/explore/assets/56753/825b8d31-54e3-4afd-99b2-7e372ae0d921">

2023-10-14 00:13 UTC, shaedrich commented
@ahpook You're very welcome&mdash;always a please to contribute!

Cool, I checked my changes and was wondering if the list parsing was intensional:
| Actual | Expected |
|-|-|
| ![grafik](https://github.com/github/explore/assets/11225821/9714b28b-267b-49be-b2cc-28816ca8e63e) | ![grafik](https://github.com/github/explore/assets/11225821/a3b4a4cc-d1d9-4d5b-a81b-0c81d6ead1ba) |
| ![grafik](https://github.com/github/explore/assets/11225821/4bfc0fe0-b314-41e1-a48d-c0202eb0ac9f) | ![grafik](https://github.com/github/explore/assets/11225821/c96d65e1-37c4-41e1-9f0f-5189c45d69e2) |

2023-10-16 14:15 UTC, kenyonj commented
I think there is definitely a bug with the `ul`/`li` stuff, looks like we're not building those lists correctly from the markdown.
For the `git` topic page, I think it's treated differently because there is an associated event in the sidebar, GitHub Universe 2023. Whether or not that's the correct CSS to style that page, I'm not sure, but I think that's the reason that it's different.

2023-10-16 14:24 UTC, shaedrich commented
Ah, yeah, makes sense.

2023-10-18 13:20 UTC, shaedrich commented
But if you look at [the feed](https://explore-feed.github.com/feed.json), it's all inside one `<ul>`, however, delimited by `\n`

2023-10-25 10:40 UTC, shaedrich commented
@kenyonj As far as I can see, that part is not open source so I can't fix that myself and create a PR, right?

2024-01-11 23:29 UTC, shaedrich commented
Finally addressed that via https://github.com/orgs/community/discussions/86653