feat: adding collection for open sources from rwanda
github/explore pull request #4263
Opened 2024-04-05 11:38 UTC by FADHILI-Josue

### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [ ] I am not the sole author or employee of a company who created either the topic I am modifying/adding or the collection entry I am modifying/adding.

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

> Please replace this line with an explanation of why you think this topic or collection should be curated.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/main/docs

> I made a new collection named "Made In Rwanda" to help exploration of open sources made in Rwanda so that other developers from Rwanda can showcase their excellent work by adding their work in this made in Rwanda collection

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

2024-04-05 14:27 UTC, tomthorogood commented
@FADHILI-Josue thanks so much for your contribution to GitHub Explore! ✨  Could you please make sure to check the box above that says:

> I am not the sole author or employee of a company who created either the topic I am modifying/adding or the collection entry I am modifying/adding.

It also appears one of the repositories you linked has been renamed, so must be fixed before we can merge in your changes.

2024-04-08 14:33 UTC, kenyonj requested changes

2024-04-08 14:33 UTC, kenyonj commented on collections/made-in-rwanda/index.md
> +Open source projects built in or receiving significant contributions from rwanda :rwanda:
```suggestion
Open source projects built in or receiving significant contributions from Rwanda :rwanda:
```

2024-04-08 15:56 UTC, kenyonj commented on collections/made-in-rwanda/index.md
> + - mutesa-Cedric/react-swift-reveal
```suggestion
 - Mutesa-Cedric/react-swift-reveal
```

2024-04-08 15:57 UTC, kenyonj approved these changes
Looks great. Thanks for your contribution!

2024-04-08 16:00 UTC, kenyonj commented on collections/made-in-rwanda/index.md
> +created_by: FADHILI Josue
```suggestion
created_by: FADHILI Josue
```

2024-04-08 20:05 UTC, merged