Add topic: Einstein problem
github/explore pull request #4378
Opened 2024-06-19 16:48 UTC by TKanX

- Display name: Einstein problem
- Logo: einstein-problem.png
- Related: tridecco
- Short description: The Einstein problem seeks a single tile shape that can tessellate a plane only nonperiodically, known as an "einstein."
- Topic: einstein-problem
- Wikipedia URL: https://en.wikipedia.org/wiki/Einstein_problem

Included detailed description and context for the Einstein problem in plane geometry.

### Please confirm this pull request meets the following requirements:

- [x] I followed the contributing guidelines: <https://github.com/github/explore/blob/main/CONTRIBUTING.md>.
- [x] I am not the sole author or employee of a company who created either the topic I am modifying/adding or the collection entry I am modifying/adding.

### Which change are you proposing?

  - [ ] Suggesting edits to an existing topic or collection
  - [x] Curating a new topic or collection
  - [ ] Something that does not neatly fit into the binary options above

---

### Editing an existing topic or collection

I'm suggesting these edits to an existing topic or collection:
- [ ] Image (and my file is `*.png`, square, dimensions 288x288, size <= 75 kB)
- [ ] Content (and my changes are in `index.md`)

> Please replace this line with an explanation of why you think these changes should be made.

### Curating a new topic or collection

- [x] I've formatted my changes as a new folder directory, named for the topic or collection as it appears in the URL on GitHub (e.g. `https://github.com/topics/[NAME]` or `https://github.com/collections/[NAME]`)
- [x] My folder contains a `*.png` image (if applicable) and `index.md`
- [x] All required fields in my `index.md` conform to the Style Guide and API docs: <https://github.com/github/explore/tree/main/docs>

> This pull request adds the Einstein problem topic.

### Something that does not neatly fit into the binary options above

- [ ] My suggested edits are not about an existing topic or collection, or at least not a single one
- [ ] My suggested edits are not about curating a new topic or collection, or at least not a single one
- [ ] My suggested edits conform to the Style Guide and API docs: https://github.com/github/explore/tree/main/docs

> Please replace this line with an explanation of your proposed changes.

---

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

2024-06-20 20:54 UTC, tomthorogood commented
@tkanx I think the Einstein Problem is a valid topic, but would you mind removing Tridecco as a topic for this PR? If Tridecco is OSS, I think it could belong to one of the existing [collections](https://github.com/github/explore/tree/main/collections), and encourage you to open a second pull request to add Tridecco's source code to the appropriate collection, or create a new collection if you think there is no good place for Tridecco currently.

Once the Einstein Problem topic is merged in, you can also tag the Tridecco repository with that topic (if Tridecco's source code is open sources on GitHub)

Thank you!

2024-06-20 20:55 UTC, tomthorogood requested changes
I would be happy to merge in the Einstein Problem as a topic, once Tridecco is removed as a topic inside this PR. Thank you! 🙌

2024-06-21 13:55 UTC, jmeridth approved these changes

2024-06-21 19:26 UTC, tomthorogood approved these changes

2024-06-21 19:27 UTC, merged